DROP TABLE IF EXISTS booking_statuses;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS bookings;
DROP TABLE IF EXISTS slots;
DROP TABLE IF EXISTS schedules;
DROP TABLE IF EXISTS rooms;
DROP TABLE IF EXISTS users;


